apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterhealthchecktemplates.onsen.cattle.io
spec:
  group: onsen.cattle.io
  names:
    kind: ClusterHealthCheckTemplate
    plural: clusterhealthchecktemplates
    singular: clusterhealthchecktemplate
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              option:
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
